### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/TextParse.jl#146]
@ViralBShah I just tried to enable some GitHub Actions on this repo, but I'm getting a message that the billing plan for this organization doesn't support Github Actions. I guess that is the billing plan for JuliaComputing?

Not sure what the options are. Can you enable github actions on this repo? But in a way that is free for you guys? That would be the easiest. If that doesn't work, would it make sense to move this repo into an org that does have free Github Actions? Maybe github.com/queryverse, where I have all my other packages? I've pretty much taken over the package in any case over the last 1.5 years or so :)

I don't really care how we solve this, as long as we can enable Github Actions :)

Also CCing @shashi

**Comment by ViralBShah** [comment]
@aviks Do you know what needs to be done? We are probably on an old github plan (that is cost-effective). If necessary, happy to move the repo to a more convenient org.

**Comment by aviks** [comment]
I think the best thing to do is to move this repo to another org.

**Comment by ViralBShah** [comment]
Even JuliaDB? Any existing orgs or new? @quinnj ?

**Comment by davidanthoff** [comment]
If we move things, then my preference would be that we move TextParse.jl into https://github.com/queryverse. I've been the main contributor for quite a while now, and I plan to continue to work on it, and having all my packages in one place makes things easier for me.

I've got no opinion on JuliaDB or IndexedTables, I've not worked on either, so I don't think queryverse would be a good home.

**Comment by quinnj** [comment]
We could move IndexedTables and JuliaDB to JuliaData. I'm fine w/ moving TextParse.jl to queryverse, since, as David mentioned, he's the only contributor to it for a while now.

**Comment by davidanthoff** [comment]
Cool, sounds like a plan.

I just checked, and I can't initiate the transfer because I don't have the necessary rights here. So either someone gives me more rights on this repo here (or do they need to be in the org?), or I can give temporary rights to queryverse to someone who can start the transfer from this repo here.

Oh, and we should probably also check with @shashi, he of course did all the initial implementation!

**Comment by ViralBShah** [comment]
I am sure @shashi is ok with it. @davidanthoff Do you want to give me owner on queryverse, and @quinnj if you give me owner on JuliaData, I will move all the relevant packages.

cc @JeffBezanson @StefanKarpinski also.

**Comment by davidanthoff** [comment]
Done, @ViralBShah you should have owner rights at queryverse.

**Comment by ViralBShah** [comment]
Transferred. Please feel free to remove me as owner.

**Comment by davidanthoff** [comment]
Perfect, thanks! Yes, I'll take care of the registry update.
